// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ggum_grad
NumericVector ggum_grad(arma::colvec par, arma::mat Theta, int D, int C, arma::colvec Z);
RcppExport SEXP _mirt_ggum_grad(SEXP parSEXP, SEXP ThetaSEXP, SEXP DSEXP, SEXP CSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< int >::type C(CSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(ggum_grad(par, Theta, D, C, Z));
    return rcpp_result_gen;
END_RCPP
}
