# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ggum_grad <- function(par, Theta, D, C, Z) {
    .Call('_mirt_ggum_grad', PACKAGE = 'mirt', par, Theta, D, C, Z)
}

